app:
  core:
    info:
      name: MangaList
      description: MangaList backend
      version: ${project.version}
spring:
  jpa:
    database: postgresql
#    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/MangaList
  main:
    allow-bean-definition-overriding: true
