server:
  port: 8080
  servlet:
    context-path: /mangalist
spring:
  application:
    name: ${app.core.info.name}
  jpa:
    database: postgresql
#    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/MangaList
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
app:
  webapp:
    cors:
      allowed-origins:
        - "http://localhost:4200"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      allowed-headers:
#        - Authorization
        - "*"
#      allow-credentials: true
      exposed-headers:
#        - Authorization
        - "*"
  core:
    info:
      name: MangaList
      description: MangaList backend
      version: ${project.version}
logging:
  pattern:
    console: "%clr(%d){cyan} [%clr(%p)] %clr(%c){magenta} - %m%n"
